BEGIN;

CREATE TABLE organizations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  slug varchar(63) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT organizations_slug_format CHECK (
    slug ~ '^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$'
  )
);

CREATE UNIQUE INDEX organizations_slug_normalized_key
  ON organizations (lower(slug));

INSERT INTO organizations (name, slug)
VALUES ('Основная организация', 'main');

ALTER TABLE departments ADD COLUMN organization_id bigint;
ALTER TABLE positions ADD COLUMN organization_id bigint;
ALTER TABLE responsibilities ADD COLUMN organization_id bigint;
ALTER TABLE business_functions ADD COLUMN organization_id bigint;
ALTER TABLE regulations ADD COLUMN organization_id bigint;
ALTER TABLE regulation_versions ADD COLUMN organization_id bigint;
ALTER TABLE roles ADD COLUMN organization_id bigint;
ALTER TABLE position_responsibilities ADD COLUMN organization_id bigint;
ALTER TABLE responsibility_functions ADD COLUMN organization_id bigint;
ALTER TABLE function_regulations ADD COLUMN organization_id bigint;
ALTER TABLE role_permissions ADD COLUMN organization_id bigint;

UPDATE departments SET organization_id = (SELECT id FROM organizations WHERE slug = 'main');
UPDATE positions SET organization_id = (SELECT id FROM organizations WHERE slug = 'main');
UPDATE responsibilities SET organization_id = (SELECT id FROM organizations WHERE slug = 'main');
UPDATE business_functions SET organization_id = (SELECT id FROM organizations WHERE slug = 'main');
UPDATE regulations SET organization_id = (SELECT id FROM organizations WHERE slug = 'main');
UPDATE regulation_versions rv
SET organization_id = r.organization_id
FROM regulations r
WHERE r.id = rv.regulation_id;
UPDATE roles SET organization_id = (SELECT id FROM organizations WHERE slug = 'main');
UPDATE position_responsibilities pr
SET organization_id = p.organization_id
FROM positions p
WHERE p.id = pr.position_id;
UPDATE responsibility_functions rf
SET organization_id = r.organization_id
FROM responsibilities r
WHERE r.id = rf.responsibility_id;
UPDATE function_regulations fr
SET organization_id = f.organization_id
FROM business_functions f
WHERE f.id = fr.function_id;
UPDATE role_permissions rp
SET organization_id = r.organization_id
FROM roles r
WHERE r.id = rp.role_id;

ALTER TABLE departments ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE positions ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE responsibilities ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE business_functions ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE regulations ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE regulation_versions ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE roles ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE position_responsibilities ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE responsibility_functions ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE function_regulations ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE role_permissions ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE departments DROP CONSTRAINT departments_name_key;
ALTER TABLE positions DROP CONSTRAINT positions_name_key;
ALTER TABLE responsibilities DROP CONSTRAINT responsibilities_name_key;
ALTER TABLE business_functions DROP CONSTRAINT business_functions_name_key;
ALTER TABLE roles DROP CONSTRAINT roles_name_key;

ALTER TABLE departments ADD CONSTRAINT departments_organization_name_key UNIQUE (organization_id, name);
ALTER TABLE positions ADD CONSTRAINT positions_organization_name_key UNIQUE (organization_id, name);
ALTER TABLE responsibilities ADD CONSTRAINT responsibilities_organization_name_key UNIQUE (organization_id, name);
ALTER TABLE business_functions ADD CONSTRAINT business_functions_organization_name_key UNIQUE (organization_id, name);
ALTER TABLE roles ADD CONSTRAINT roles_organization_name_key UNIQUE (organization_id, name);

ALTER TABLE departments ADD CONSTRAINT departments_organization_id_id_key UNIQUE (organization_id, id);
ALTER TABLE positions ADD CONSTRAINT positions_organization_id_id_key UNIQUE (organization_id, id);
ALTER TABLE responsibilities ADD CONSTRAINT responsibilities_organization_id_id_key UNIQUE (organization_id, id);
ALTER TABLE business_functions ADD CONSTRAINT business_functions_organization_id_id_key UNIQUE (organization_id, id);
ALTER TABLE regulations ADD CONSTRAINT regulations_organization_id_id_key UNIQUE (organization_id, id);
ALTER TABLE roles ADD CONSTRAINT roles_organization_id_id_key UNIQUE (organization_id, id);

ALTER TABLE departments
  ADD CONSTRAINT fk_departments_organization
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE positions
  ADD CONSTRAINT fk_positions_organization
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE responsibilities
  ADD CONSTRAINT fk_responsibilities_organization
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE business_functions
  ADD CONSTRAINT fk_business_functions_organization
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE regulations
  ADD CONSTRAINT fk_regulations_organization
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE regulation_versions
  ADD CONSTRAINT fk_regulation_versions_organization
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE roles
  ADD CONSTRAINT fk_roles_organization
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

ALTER TABLE departments DROP CONSTRAINT fk_department_parent;
ALTER TABLE departments
  ADD CONSTRAINT fk_department_parent
  FOREIGN KEY (organization_id, parent_department_id)
  REFERENCES departments(organization_id, id);

ALTER TABLE position_responsibilities DROP CONSTRAINT fk_position_responsibility_position;
ALTER TABLE position_responsibilities DROP CONSTRAINT fk_position_responsibility_responsibility;
ALTER TABLE position_responsibilities
  ADD CONSTRAINT fk_position_responsibility_position
  FOREIGN KEY (organization_id, position_id)
  REFERENCES positions(organization_id, id) ON DELETE CASCADE;
ALTER TABLE position_responsibilities
  ADD CONSTRAINT fk_position_responsibility_responsibility
  FOREIGN KEY (organization_id, responsibility_id)
  REFERENCES responsibilities(organization_id, id) ON DELETE CASCADE;

ALTER TABLE responsibility_functions DROP CONSTRAINT fk_responsibility_function_responsibility;
ALTER TABLE responsibility_functions DROP CONSTRAINT fk_responsibility_function_function;
ALTER TABLE responsibility_functions
  ADD CONSTRAINT fk_responsibility_function_responsibility
  FOREIGN KEY (organization_id, responsibility_id)
  REFERENCES responsibilities(organization_id, id) ON DELETE CASCADE;
ALTER TABLE responsibility_functions
  ADD CONSTRAINT fk_responsibility_function_function
  FOREIGN KEY (organization_id, function_id)
  REFERENCES business_functions(organization_id, id) ON DELETE CASCADE;

ALTER TABLE function_regulations DROP CONSTRAINT fk_function_regulation_function;
ALTER TABLE function_regulations DROP CONSTRAINT fk_function_regulation_regulation;
ALTER TABLE function_regulations
  ADD CONSTRAINT fk_function_regulation_function
  FOREIGN KEY (organization_id, function_id)
  REFERENCES business_functions(organization_id, id) ON DELETE CASCADE;
ALTER TABLE function_regulations
  ADD CONSTRAINT fk_function_regulation_regulation
  FOREIGN KEY (organization_id, regulation_id)
  REFERENCES regulations(organization_id, id) ON DELETE CASCADE;

ALTER TABLE regulation_versions DROP CONSTRAINT fk_version_regulation;
ALTER TABLE regulation_versions
  ADD CONSTRAINT fk_version_regulation
  FOREIGN KEY (organization_id, regulation_id)
  REFERENCES regulations(organization_id, id) ON DELETE CASCADE;

ALTER TABLE role_permissions DROP CONSTRAINT fk_role_permission_role;
ALTER TABLE role_permissions
  ADD CONSTRAINT fk_role_permission_role
  FOREIGN KEY (organization_id, role_id)
  REFERENCES roles(organization_id, id) ON DELETE CASCADE;

CREATE TABLE organization_memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id bigint NOT NULL,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  department_id bigint,
  position_id bigint,
  is_owner boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT organization_memberships_organization_user_key UNIQUE (organization_id, user_id),
  CONSTRAINT organization_memberships_organization_id_id_key UNIQUE (organization_id, id),
  CONSTRAINT fk_membership_organization
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_membership_department
    FOREIGN KEY (organization_id, department_id)
    REFERENCES departments(organization_id, id),
  CONSTRAINT fk_membership_position
    FOREIGN KEY (organization_id, position_id)
    REFERENCES positions(organization_id, id)
);

INSERT INTO organization_memberships (
  organization_id,
  user_id,
  department_id,
  position_id,
  is_owner
)
SELECT
  (SELECT id FROM organizations WHERE slug = 'main'),
  u.id,
  u.department_id,
  u.position_id,
  true
FROM users u;

CREATE TABLE membership_roles (
  organization_id bigint NOT NULL,
  membership_id bigint NOT NULL,
  role_id bigint NOT NULL,
  PRIMARY KEY (organization_id, membership_id, role_id),
  CONSTRAINT fk_membership_role_membership
    FOREIGN KEY (organization_id, membership_id)
    REFERENCES organization_memberships(organization_id, id) ON DELETE CASCADE,
  CONSTRAINT fk_membership_role_role
    FOREIGN KEY (organization_id, role_id)
    REFERENCES roles(organization_id, id) ON DELETE CASCADE
);

INSERT INTO membership_roles (organization_id, membership_id, role_id)
SELECT om.organization_id, om.id, ur.role_id
FROM user_roles ur
JOIN organization_memberships om ON om.user_id = ur.user_id
JOIN roles r ON r.id = ur.role_id AND r.organization_id = om.organization_id;

INSERT INTO membership_roles (organization_id, membership_id, role_id)
SELECT om.organization_id, om.id, r.id
FROM organization_memberships om
JOIN roles r ON r.organization_id = om.organization_id AND r.name = 'admin'
WHERE om.is_owner
ON CONFLICT DO NOTHING;

CREATE TABLE membership_responsibilities (
  organization_id bigint NOT NULL,
  membership_id bigint NOT NULL,
  responsibility_id bigint NOT NULL,
  assigned_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (organization_id, membership_id, responsibility_id),
  CONSTRAINT fk_membership_responsibility_membership
    FOREIGN KEY (organization_id, membership_id)
    REFERENCES organization_memberships(organization_id, id) ON DELETE CASCADE,
  CONSTRAINT fk_membership_responsibility_responsibility
    FOREIGN KEY (organization_id, responsibility_id)
    REFERENCES responsibilities(organization_id, id) ON DELETE CASCADE
);

INSERT INTO membership_responsibilities (
  organization_id,
  membership_id,
  responsibility_id,
  assigned_at
)
SELECT om.organization_id, om.id, ur.responsibility_id, ur.assigned_at
FROM user_responsibilities ur
JOIN organization_memberships om ON om.user_id = ur.user_id
JOIN responsibilities r
  ON r.id = ur.responsibility_id
 AND r.organization_id = om.organization_id;

ALTER TABLE regulations ADD COLUMN created_by_membership_id bigint;
UPDATE regulations r
SET created_by_membership_id = om.id
FROM organization_memberships om
WHERE om.user_id = r.created_by
  AND om.organization_id = r.organization_id;
ALTER TABLE regulations DROP CONSTRAINT fk_regulation_creator;
ALTER TABLE regulations DROP COLUMN created_by;
ALTER TABLE regulations
  ADD CONSTRAINT fk_regulation_creator_membership
  FOREIGN KEY (organization_id, created_by_membership_id)
  REFERENCES organization_memberships(organization_id, id);

ALTER TABLE regulation_versions ADD COLUMN created_by_membership_id bigint;
ALTER TABLE regulation_versions ADD COLUMN approved_by_membership_id bigint;
UPDATE regulation_versions rv
SET created_by_membership_id = om.id
FROM organization_memberships om
WHERE om.user_id = rv.created_by
  AND om.organization_id = rv.organization_id;
UPDATE regulation_versions rv
SET approved_by_membership_id = om.id
FROM organization_memberships om
WHERE om.user_id = rv.approved_by
  AND om.organization_id = rv.organization_id;
ALTER TABLE regulation_versions DROP CONSTRAINT fk_version_creator;
ALTER TABLE regulation_versions DROP CONSTRAINT fk_version_approver;
ALTER TABLE regulation_versions DROP COLUMN created_by;
ALTER TABLE regulation_versions DROP COLUMN approved_by;
ALTER TABLE regulation_versions
  ADD CONSTRAINT fk_version_creator_membership
  FOREIGN KEY (organization_id, created_by_membership_id)
  REFERENCES organization_memberships(organization_id, id);
ALTER TABLE regulation_versions
  ADD CONSTRAINT fk_version_approver_membership
  FOREIGN KEY (organization_id, approved_by_membership_id)
  REFERENCES organization_memberships(organization_id, id);

ALTER TABLE users DROP CONSTRAINT fk_user_department;
ALTER TABLE users DROP CONSTRAINT fk_user_position;
ALTER TABLE users DROP COLUMN department_id;
ALTER TABLE users DROP COLUMN position_id;
DROP TABLE user_roles;
DROP TABLE user_responsibilities;

CREATE INDEX idx_memberships_user_active
  ON organization_memberships (user_id, is_active);
CREATE INDEX idx_memberships_organization_active
  ON organization_memberships (organization_id, is_active);
CREATE INDEX idx_position_responsibilities_organization
  ON position_responsibilities (organization_id);
CREATE INDEX idx_responsibility_functions_organization
  ON responsibility_functions (organization_id);
CREATE INDEX idx_function_regulations_organization
  ON function_regulations (organization_id);
CREATE INDEX idx_role_permissions_organization
  ON role_permissions (organization_id);
CREATE INDEX idx_regulations_organization_status
  ON regulations (organization_id, status);
CREATE INDEX idx_regulation_versions_organization_regulation
  ON regulation_versions (organization_id, regulation_id);

GRANT SELECT, INSERT, UPDATE, DELETE
  ON organizations, organization_memberships, membership_roles, membership_responsibilities
  TO business_user;
GRANT USAGE, SELECT
  ON SEQUENCE organizations_id_seq, organization_memberships_id_seq
  TO business_user;

COMMIT;
