BEGIN;

CREATE TABLE audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  request_id uuid,
  actor_membership_id bigint REFERENCES organization_memberships(id) ON DELETE SET NULL,
  actor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_name varchar(255),
  actor_email varchar(254),
  action varchar(32) NOT NULL,
  entity_type varchar(128) NOT NULL,
  entity_id varchar(255),
  changes jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX audit_logs_organization_created_idx
  ON audit_logs (organization_id, created_at DESC, id DESC);
CREATE INDEX audit_logs_organization_actor_idx
  ON audit_logs (organization_id, actor_membership_id, created_at DESC);
CREATE INDEX audit_logs_organization_entity_idx
  ON audit_logs (organization_id, entity_type, entity_id, created_at DESC);
CREATE INDEX audit_logs_request_idx
  ON audit_logs (request_id) WHERE request_id IS NOT NULL;

INSERT INTO permissions (code, name, description)
VALUES ('log.view', 'Просмотр журнала действий', 'Просмотр истории изменений и действий пользователей')
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permissions (organization_id, role_id, permission_id)
SELECT r.organization_id, r.id, p.id
FROM roles r
JOIN permissions p ON p.code = 'log.view'
WHERE r.name = 'admin'
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION audit_safe_snapshot(table_name text, snapshot jsonb)
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT (CASE
    WHEN snapshot IS NULL THEN NULL
    WHEN table_name = 'users' THEN snapshot - 'password_hash'
    WHEN table_name = 'regulation_versions' THEN
      snapshot - 'content' || jsonb_build_object(
        'content_length', length(COALESCE(snapshot ->> 'content', ''))
      )
    ELSE snapshot
  END) - 'created_at' - 'updated_at';
$$;

CREATE OR REPLACE FUNCTION audit_row_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  context jsonb := COALESCE(
    NULLIF(current_setting('app.audit_context', true), '')::jsonb,
    '{}'::jsonb
  );
  old_snapshot jsonb;
  new_snapshot jsonb;
  record_snapshot jsonb;
  change_set jsonb;
  target_organization_id bigint;
  target_entity_id text;
BEGIN
  -- Organizations are deactivated by the application. A physical DELETE cannot
  -- append a child log row after the parent has gone because of the tenant FK.
  IF TG_TABLE_NAME = 'organizations' AND TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  old_snapshot := audit_safe_snapshot(TG_TABLE_NAME, CASE WHEN TG_OP <> 'INSERT' THEN to_jsonb(OLD) ELSE NULL END);
  new_snapshot := audit_safe_snapshot(TG_TABLE_NAME, CASE WHEN TG_OP <> 'DELETE' THEN to_jsonb(NEW) ELSE NULL END);
  record_snapshot := COALESCE(new_snapshot, old_snapshot, '{}'::jsonb);

  IF TG_OP = 'UPDATE' THEN
    SELECT COALESCE(jsonb_object_agg(key, jsonb_build_object('before', old_snapshot -> key, 'after', value)), '{}'::jsonb)
    INTO change_set
    FROM jsonb_each(new_snapshot)
    WHERE old_snapshot -> key IS DISTINCT FROM value;

    IF TG_TABLE_NAME = 'users' AND to_jsonb(OLD) -> 'password_hash' IS DISTINCT FROM to_jsonb(NEW) -> 'password_hash' THEN
      change_set := change_set || jsonb_build_object('password_changed', jsonb_build_object('before', false, 'after', true));
    END IF;
  ELSIF TG_OP = 'INSERT' THEN
    change_set := jsonb_build_object('after', new_snapshot);
  ELSE
    change_set := jsonb_build_object('before', old_snapshot);
  END IF;

  target_organization_id := CASE
    WHEN TG_TABLE_NAME = 'organizations' THEN NULLIF(record_snapshot ->> 'id', '')::bigint
    ELSE COALESCE(
      NULLIF(record_snapshot ->> 'organization_id', '')::bigint,
      NULLIF(context ->> 'organizationId', '')::bigint
    )
  END;

  IF target_organization_id IS NULL THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  -- During a physical organization delete, cascading child triggers run while
  -- the parent row is already unavailable. The application uses soft delete;
  -- skip these maintenance-only cascade records to preserve FK integrity.
  IF NOT EXISTS (SELECT 1 FROM organizations WHERE id = target_organization_id) THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  target_entity_id := COALESCE(
    record_snapshot ->> 'id',
    record_snapshot ->> 'membership_id',
    record_snapshot ->> 'role_id',
    record_snapshot ->> 'responsibility_id',
    record_snapshot ->> 'function_id',
    record_snapshot ->> 'regulation_id',
    record_snapshot ->> 'user_id'
  );

  INSERT INTO audit_logs (
    organization_id, request_id, actor_membership_id, actor_user_id,
    actor_name, actor_email, action, entity_type, entity_id, changes, metadata
  ) VALUES (
    target_organization_id,
    NULLIF(context ->> 'requestId', '')::uuid,
    NULLIF(context ->> 'membershipId', '')::bigint,
    NULLIF(context ->> 'userId', '')::bigint,
    COALESCE(NULLIF(context ->> 'actorName', ''), 'Системное изменение'),
    NULLIF(context ->> 'actorEmail', ''),
    lower(TG_OP),
    TG_TABLE_NAME,
    target_entity_id,
    change_set,
    context - ARRAY['organizationId', 'membershipId', 'userId', 'actorName', 'actorEmail']
  );

  RETURN COALESCE(NEW, OLD);
END;
$$;

DO $$
DECLARE
  table_name text;
  audited_tables text[] := ARRAY[
    'organizations', 'users', 'organization_memberships',
    'departments', 'positions', 'responsibilities', 'business_functions',
    'roles', 'membership_roles', 'membership_responsibilities',
    'role_permissions', 'position_responsibilities', 'responsibility_functions',
    'regulations', 'regulation_versions', 'function_regulations'
  ];
BEGIN
  FOREACH table_name IN ARRAY audited_tables LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS audit_row_change_trigger ON %I', table_name);
    EXECUTE format(
      'CREATE TRIGGER audit_row_change_trigger AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION audit_row_change()',
      table_name
    );
  END LOOP;
END;
$$;

GRANT SELECT, INSERT ON audit_logs TO business_user;
GRANT USAGE, SELECT ON SEQUENCE audit_logs_id_seq TO business_user;

COMMIT;
